sudo: required
services: 
  - docker
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in multicontainer-k8s-e29f3f8bff90.json.enc -out multicontainer-k8s-e29f3f8bff90.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multicontainer-k8s-e29f3f8bff90.json
  - gcloud config set project multicontainer-k8s
  - gcloud config set compute/zone europe-west1-b
  - gcloud container clusters get-credentials multicontainer-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t peinutz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run peinutz/react-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

